### ISSUE TITLE
Nama Folder Kurang Tepat

### ISSUE THREAD

**Issue by hadihammurabi** [novicefrontendev/naya-kursus#1]
Dalam File ini:
* https://github.com/novicefrontendev/naya-kursus/blob/master/02-01/README.md
* https://github.com/novicefrontendev/naya-kursus/blob/master/02-02/README.md

tertulis minggu 3, tetapi di folder 02.

**Comment by novicefrontendev** [comment]
Maaf Mas, kemarin saya lupa ngeganti nama foldernya jadi minggu ke-3 terus saya juga lupa mindah folder project di minggu ke-2. Saya ganti revisi lagi Mas. Terimakasih..
